import { ClubsType } from "@/types";

const clubsList: ClubsType[]  = [
  {
    id: 1,
    name: "Al Ahly",
    image: "/team-logo/alahly.svg",
    sloganName: "Red Devils",
    player: [
      {
        id: 1,
        name: "Mohamed El-Shenawy",
        age: 34,
        position: "Goalkeeper",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 1,
          teamName: "Al Ahly",
          teamLogo: "/team-logo/alahly.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 1,
        stats: [{ matches: 20, goals: 0, assists: 0 }],
      },
      {
        id: 2,
        name: "Ayman Ashraf",
        age: 30,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 1,
          teamName: "Al Ahly",
          teamLogo: "/team-logo/alahly.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 5,
        stats: [{ matches: 15, goals: 1, assists: 2 }],
      },
      {
        id: 3,
        name: "Ali Maaloul",
        age: 31,
        position: "Defender",
        contryCode: "TN",
        preferredFoot: "Left",
        club: {
          teamId: 1,
          teamName: "Al Ahly",
          teamLogo: "/team-logo/alahly.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 24,
        stats: [{ matches: 18, goals: 3, assists: 5 }],
      },
    ],
  },
  {
    id: 2,
    name: "Zamalek",
    image: "/team-logo/zamalek.svg",
    sloganName: "White Knights",
    player: [
      {
        id: 6,
        name: "Mohamed Awad",
        age: 30,
        position: "Goalkeeper",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 2,
          teamName: "Zamalek",
          teamLogo: '/team-logo/zamalek.svg',
        },
        image: "/nile-player-card.png",
        kitNumber: 16,
        stats: [{ matches: 18, goals: 0, assists: 0 }],
      },
      {
        id: 7,
        name: "Ahmed Fathi",
        age: 33,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 2,
          teamName: "Zamalek",
          teamLogo: '/team-logo/zamalek.svg',
        },
        image: "/nile-player-card.png",
        kitNumber: 2,
        stats: [{ matches: 19, goals: 1, assists: 2 }],
      },
      {
        id: 8,
        name: "Tariq Hamed",
        age: 32,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 2,
          teamName: "Zamalek",
          teamLogo: '/team-logo/zamalek.svg',
        },
        image: "/nile-player-card.png",
        kitNumber: 6,
        stats: [{ matches: 21, goals: 4, assists: 3 }],
      },
    ],
  },
  {
    id: 3,
    name: "Ismaily",
    image: "/team-logo/ismaily.svg",
    sloganName: "Brazilian Egypt",
    player: [
      {
        id: 9,
        name: "Ahmed Fathy",
        age: 28,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 3,
          teamName: "Ismaily",
          teamLogo: "/team-logo/ismaily.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 8,
        stats: [{ matches: 22, goals: 5, assists: 3 }],
      },
      {
        id: 10,
        name: "Mohamed Salah",
        age: 33,
        position: "Forward",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 3,
          teamName: "Ismaily",
          teamLogo: "/team-logo/ismaily.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 11,
        stats: [{ matches: 15, goals: 7, assists: 5 }],
      },
      {
        id: 11,
        name: "Hossam Hassan",
        age: 30,
        position: "Striker",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 3,
          teamName: "Ismaily",
          teamLogo: "/team-logo/ismaily.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 9,
        stats: [{ matches: 17, goals: 6, assists: 2 }],
      },
    ],
  },
  {
    id: 4,
    name: "Al Masry",
    image: "/team-logo/almasry.svg",
    sloganName: "Green Eagles",
    player: [
      {
        id: 12,
        name: "Ahmed Ramy",
        age: 26,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 4,
          teamName: "Al Masry",
          teamLogo: "/team-logo/almasry.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 6,
        stats: [{ matches: 20, goals: 2, assists: 3 }],
      },
      {
        id: 13,
        name: "Amr Gamal",
        age: 29,
        position: "Forward",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 4,
          teamName: "Al Masry",
          teamLogo: "/team-logo/almasry.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 14,
        stats: [{ matches: 21, goals: 10, assists: 4 }],
      },
      {
        id: 14,
        name: "Mohamed Gomaa",
        age: 27,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 4,
          teamName: "Al Masry",
          teamLogo: "/team-logo/almasry.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 8,
        stats: [{ matches: 19, goals: 4, assists: 2 }],
      },
    ],
  },
  {
    id: 5,
    name: "Ghazl El Mahalla",
    image: "/team-logo/ghazl.svg",
    sloganName: "Leader of the Delta",
    player: [
      {
        id: 15,
        name: "Hany Said",
        age: 30,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 5,
          teamName: "Ghazl El Mahalla",
          teamLogo: "/team-logo/ghazl.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 4,
        stats: [{ matches: 18, goals: 1, assists: 1 }],
      },
      {
        id: 16,
        name: "Mohamed Salah",
        age: 25,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 5,
          teamName: "Ghazl El Mahalla",
          teamLogo: "/team-logo/ghazl.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 10,
        stats: [{ matches: 17, goals: 3, assists: 2 }],
      },
      {
        id: 17,
        name: "Ahmed Mostafa",
        age: 28,
        position: "Forward",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 5,
          teamName: "Ghazl El Mahalla",
          teamLogo: "/team-logo/ghazl.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 7,
        stats: [{ matches: 22, goals: 5, assists: 3 }],
      },
    ],
  },
  {
    id: 6,
    name: "Pyramids",
    image: "/team-logo/pyramids.svg",
    sloganName: "Sky Blues",
    player: [
      {
        id: 18,
        name: "Ahmed Hegazy",
        age: 32,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 6,
          teamName: "Pyramids",
          teamLogo: "/team-logo/pyramids.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 4,
        stats: [{ matches: 25, goals: 1, assists: 2 }],
      },
      {
        id: 19,
        name: "Ali Gabr",
        age: 30,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 6,
          teamName: "Pyramids",
          teamLogo: "/team-logo/pyramids.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 5,
        stats: [{ matches: 21, goals: 2, assists: 1 }],
      },
      {
        id: 20,
        name: "Mohamed Farouk",
        age: 27,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 6,
          teamName: "Pyramids",
          teamLogo: "/team-logo/pyramids.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 8,
        stats: [{ matches: 24, goals: 3, assists: 4 }],
      },
    ],
  },
  {
    id: 7,
    name: "Al Ittihad Alexandria",
    image: "/team-logo/alittihad.svg",
    sloganName: "Master of the Country",
    player: [
      {
        id: 21,
        name: "Mohamed El-Sayed",
        age: 29,
        position: "Goalkeeper",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 7,
          teamName: "Al Ittihad Alexandria",
          teamLogo: "/team-logo/alittihad.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 1,
        stats: [{ matches: 20, goals: 0, assists: 0 }],
      },
      {
        id: 22,
        name: "Ali Ahmed",
        age: 27,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 7,
          teamName: "Al Ittihad Alexandria",
          teamLogo: "/team-logo/alittihad.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 6,
        stats: [{ matches: 22, goals: 1, assists: 1 }],
      },
      {
        id: 23,
        name: "Mohamed Samy",
        age: 31,
        position: "Forward",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 7,
          teamName: "Al Ittihad Alexandria",
          teamLogo: "/team-logo/alittihad.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 9,
        stats: [{ matches: 18, goals: 7, assists: 3 }],
      },
    ],
  },
  {
    id: 8,
    name: "Smouha",
    image: "/team-logo/smouha.svg",
    sloganName: "Alexandrian Blues",
    player: [
      {
        id: 24,
        name: "Mohamed Hossam",
        age: 29,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 8,
          teamName: "Smouha",
          teamLogo: "/team-logo/smouha.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 10,
        stats: [{ matches: 20, goals: 3, assists: 2 }],
      },
      {
        id: 25,
        name: "Ahmed El-Mahdy",
        age: 32,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 8,
          teamName: "Smouha",
          teamLogo: "/team-logo/smouha.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 4,
        stats: [{ matches: 21, goals: 0, assists: 1 }],
      },
      {
        id: 26,
        name: "Tamer Hossam",
        age: 27,
        position: "Forward",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 8,
          teamName: "Smouha",
          teamLogo: "/team-logo/smouha.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 11,
        stats: [{ matches: 22, goals: 8, assists: 4 }],
      },
    ],
  },
  {
    id: 9,
    name: "Ceramica Cleopatra",
    image: "/team-logo/ceramica.svg",
    sloganName: "The Pottery Makers",
    player: [
      {
        id: 27,
        name: "Ahmed Sayed",
        age: 30,
        position: "Goalkeeper",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 9,
          teamName: "Ceramica Cleopatra",
          teamLogo: "/team-logo/ceramica.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 1,
        stats: [{ matches: 20, goals: 0, assists: 0 }],
      },
      {
        id: 28,
        name: "Mahmoud Abdel-Razek",
        age: 29,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 9,
          teamName: "Ceramica Cleopatra",
          teamLogo: "/team-logo/ceramica.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 8,
        stats: [{ matches: 23, goals: 4, assists: 5 }],
      },
      {
        id: 29,
        name: "Mohamed Soliman",
        age: 25,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 9,
          teamName: "Ceramica Cleopatra",
          teamLogo: "/team-logo/ceramica.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 5,
        stats: [{ matches: 19, goals: 2, assists: 1 }],
      },
    ],
  },
  {
    id: 10,
    name: "modren FC",
    image: "/team-logo/modren.svg",
    sloganName: "modren Stars",
    player: [
      {
        id: 30,
        name: "Mohamed Tarek",
        age: 28,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 10,
          teamName: "modren FC",
          teamLogo: "/team-logo/modren.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 7,
        stats: [{ matches: 21, goals: 2, assists: 3 }],
      },
      {
        id: 31,
        name: "Ahmed Amr",
        age: 30,
        position: "Forward",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 10,
          teamName: "modren FC",
          teamLogo: "/team-logo/modren.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 9,
        stats: [{ matches: 24, goals: 6, assists: 2 }],
      },
      {
        id: 32,
        name: "Mohamed Zaki",
        age: 27,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 10,
          teamName: "modren FC",
          teamLogo: "/team-logo/modren.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 6,
        stats: [{ matches: 20, goals: 1, assists: 2 }],
      },
    ],
  },
  {
    id: 11,
    name: "Petrojet",
    image: "/team-logo/petrojet.svg",
    sloganName: "Oil Workers",
    player: [
      {
        id: 33,
        name: "Mohamed Ramadan",
        age: 30,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 11,
          teamName: "Petrojet",
          teamLogo: "/team-logo/petrojet.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 4,
        stats: [{ matches: 18, goals: 1, assists: 2 }],
      },
      {
        id: 34,
        name: "Ahmed El-Shenawy",
        age: 32,
        position: "Goalkeeper",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 11,
          teamName: "Petrojet",
          teamLogo: "/team-logo/petrojet.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 1,
        stats: [{ matches: 25, goals: 0, assists: 0 }],
      },
      {
        id: 35,
        name: "Mohamed Salah",
        age: 28,
        position: "Forward",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 11,
          teamName: "Petrojet",
          teamLogo: "/team-logo/petrojet.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 11,
        stats: [{ matches: 20, goals: 7, assists: 4 }],
      },
    ],
  },
  {
    id: 12,
    name: "El Gouna",
    image: "/team-logo/elgouna.svg",
    sloganName: "The Beach Team",
    player: [
      {
        id: 36,
        name: "Mohamed Nagy",
        age: 29,
        position: "Goalkeeper",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 12,
          teamName: "El Gouna",
          teamLogo: "/team-logo/elgouna.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 1,
        stats: [{ matches: 15, goals: 0, assists: 0 }],
      },
      {
        id: 37,
        name: "Ahmed Mosa",
        age: 31,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 12,
          teamName: "El Gouna",
          teamLogo: "/team-logo/elgouna.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 7,
        stats: [{ matches: 20, goals: 2, assists: 3 }],
      },
      {
        id: 38,
        name: "Mohamed Farouk",
        age: 25,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 12,
          teamName: "El Gouna",
          teamLogo: "/team-logo/elgouna.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 6,
        stats: [{ matches: 22, goals: 1, assists: 1 }],
      },
    ],
  },
  {
    id: 13,
    name: "National Bank SC",
    image: "/team-logo/bank.svg",
    sloganName: "The Bankers",
    player: [
      {
        id: 39,
        name: "Ahmed Said",
        age: 30,
        position: "Goalkeeper",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 13,
          teamName: "National Bank SC",
          teamLogo: "/team-logo/bank.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 1,
        stats: [{ matches: 21, goals: 0, assists: 0 }],
      },
      {
        id: 40,
        name: "Mohamed Ali",
        age: 27,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 13,
          teamName: "National Bank SC",
          teamLogo: "/team-logo/bank.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 3,
        stats: [{ matches: 19, goals: 1, assists: 2 }],
      },
      {
        id: 41,
        name: "Hossam Hassan",
        age: 29,
        position: "Forward",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 13,
          teamName: "National Bank SC",
          teamLogo: "/team-logo/bank.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 10,
        stats: [{ matches: 20, goals: 5, assists: 3 }],
      },
    ],
  },
  {
    id: 14,
    name: "Pharco FC",
    image: "/team-logo/pharco.svg",
    sloganName: "The Orange Army",
    player: [
      {
        id: 42,
        name: "Mohamed Fathi",
        age: 28,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 14,
          teamName: "Pharco FC",
          teamLogo: "/team-logo/pharco.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 6,
        stats: [{ matches: 18, goals: 0, assists: 1 }],
      },
      {
        id: 43,
        name: "Ahmed Khaled",
        age: 26,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 14,
          teamName: "Pharco FC",
          teamLogo: "/team-logo/pharco.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 8,
        stats: [{ matches: 23, goals: 4, assists: 5 }],
      },
      {
        id: 44,
        name: "Mohamed Osama",
        age: 30,
        position: "Forward",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 14,
          teamName: "Pharco FC",
          teamLogo: "/team-logo/pharco.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 9,
        stats: [{ matches: 22, goals: 7, assists: 4 }],
      },
    ],
  },
  {
    id: 15,
    name: "ENPPI",
    image: "/team-logo/enppi.svg",
    sloganName: "The Petroleum Club",
    player: [
      {
        id: 45,
        name: "Ali Mohamed",
        age: 27,
        position: "Goalkeeper",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 15,
          teamName: "ENPPI",
          teamLogo: "/team-logo/enppi.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 1,
        stats: [{ matches: 20, goals: 0, assists: 0 }],
      },
      {
        id: 46,
        name: "Ahmed Gedo",
        age: 32,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 15,
          teamName: "ENPPI",
          teamLogo: "/team-logo/enppi.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 5,
        stats: [{ matches: 18, goals: 2, assists: 1 }],
      },
      {
        id: 47,
        name: "Mohamed Shamy",
        age: 29,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 15,
          teamName: "ENPPI",
          teamLogo: "/team-logo/enppi.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 7,
        stats: [{ matches: 22, goals: 3, assists: 5 }],
      },
    ],
  },
  {
    id: 16,
    name: "ZED FC",
    image: "/team-logo/zed.svg",
    sloganName: "The Rising Stars",
    player: [
      {
        id: 48,
        name: "Mohamed Tarek",
        age: 28,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 16,
          teamName: "ZED FC",
          teamLogo: "/team-logo/zed.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 10,
        stats: [{ matches: 23, goals: 4, assists: 3 }],
      },
      {
        id: 49,
        name: "Ahmed Mosa",
        age: 30,
        position: "Forward",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 16,
          teamName: "ZED FC",
          teamLogo: "/team-logo/zed.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 9,
        stats: [{ matches: 24, goals: 8, assists: 5 }],
      },
      {
        id: 50,
        name: "Ahmed Tamer",
        age: 26,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 16,
          teamName: "ZED FC",
          teamLogo: "/team-logo/zed.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 4,
        stats: [{ matches: 21, goals: 1, assists: 2 }],
      },
    ],
  },
  {
    id: 17,
    name: "Haras El Hodood",
    image: "/team-logo/haras.svg",
    sloganName: "The Border Guards",
     player: [
      {
        id: 51,
        name: "Mohamed Tarek",
        age: 28,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 17,
          teamName: "Haras El Hodood",
          teamLogo: "/team-logo/haras.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 10,
        stats: [{ matches: 23, goals: 4, assists: 3 }],
      },
      {
        id: 52,
        name: "Ahmed Mosa",
        age: 30,
        position: "Forward",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 17,
          teamName: "Haras El Hodood",
          teamLogo: "/team-logo/haras.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 9,
        stats: [{ matches: 24, goals: 8, assists: 5 }],
      },
      {
        id: 53,
        name: "Ahmed Tamer",
        age: 26,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 17,
          teamName: "Haras El Hodood",
          teamLogo: "/team-logo/haras.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 4,
        stats: [{ matches: 21, goals: 1, assists: 2 }],
      },
    ],
  },
  {
    id: 18,
    name: "Tala'ea El Gaish",
    image: "/team-logo/talaea.svg",
    sloganName: "Army Warriors",
    player:[
      {
        id: 54,
        name: "Mohamed Tarek",
        age: 28,
        position: "Midfielder",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 18,
          teamName: "Tala'ea El Gaish",
          teamLogo: "/team-logo/talaea.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 10,
        stats: [{ matches: 23, goals: 4, assists: 3 }],
      },
      {
        id: 55,
        name: "Ahmed Mosa",
        age: 30,
        position: "Forward",
        contryCode: "EG",
        preferredFoot: "Left",
        club: {
          teamId: 18,
          teamName: "Tala'ea El Gaish",
          teamLogo: "/team-logo/talaea.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 9,
        stats: [{ matches: 24, goals: 8, assists: 5 }],
      },
      {
        id: 56,
        name: "Ahmed Tamer",
        age: 26,
        position: "Defender",
        contryCode: "EG",
        preferredFoot: "Right",
        club: {
          teamId: 18,
          teamName: "Tala'ea El Gaish",
          teamLogo: "/team-logo/talaea.svg",
        },
        image: "/nile-player-card.png",
        kitNumber: 4,
        stats: [{ matches: 21, goals: 1, assists: 2 }],
      },
    ],
  },
];





export {  clubsList  };
