export 
const teamList  = [
  {
    id: 1,
    teamImg: '/team-logo/alahly.svg',
    teamName: 'al ahly',
    teamShortName: 'ASC',
    
    played: 8,
    won: 4,
    lose: 2,
    drow: 2,
    pos: 1,
    ga: 6,
    gf: 17,
    gd: 11,
    pts: 14,
  },
  {
    id: 2,
    teamImg: '/team-logo/zamalek.svg',
    teamName: 'zamalek',
    teamShortName: 'Zfc',
    played: 8,
    won: 3,
    lose: 2,
    drow: 3,
    pos: 2,
    ga: 4,
    gf: 18,
    gd: 14,
    pts: 12,
  },
  {
    id: 3,
    teamImg: '/team-logo/ismaily.svg',
    teamName: 'ismaily',
    teamShortName: 'Ifc',
    played: 8,
    won: 3,
    lose: 2,
    drow: 3,
    pos: 3,
    ga: 15,
    gf: 14,
    gd: -1,
    pts: 12,
  },
  {
    id: 4,
    teamImg: '/team-logo/almasry.svg',
    teamName: 'al masry',
    teamShortName: 'mfc',
    played: 8,
    won: 2,
    lose: 4,
    drow: 2,
    pos: 4,
    ga: 12,
    gf: 15,
    gd: 3,
    pts: 8,
  },
  {
    id: 5,
    teamImg: '/team-logo/Ghazl.svg',
    teamName: 'Ghazl El Mahalla',
    teamShortName: 'ghazl',
    played: 8,
    won: 0,
    lose: 0,
    drow: 8,
    pos: 5,
    ga: 4,
    gf: 4,
    gd: 0,
    pts: 8,
  },
]